import Head from "next/head";
import AttacksMain from "../components/attacksMain";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import styles from "../styles/Home.module.css";

export default function Attacks() {
  var title = "Attacks";
  return (
    <div className={styles.container}>
      <Header title={title} />
      <Sidebar index={2} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AttacksMain />
    </div>
  );
}
