import Head from "next/head";
import DashboardMain from "../components/dashboardMain";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import styles from "../styles/Home.module.css";

export default function Dashboard() {
  var title = "Dashboard";
  return (
    <div className={styles.container}>
      <Header title={title} />
      <Sidebar index={1} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardMain />
    </div>
  );
}
