import Head from "next/head";
import Header from "../components/header";
import LoremMain from "../components/loremMain";
import Sidebar from "../components/sidebar";
import styles from "../styles/Home.module.css";

export default function Lorem() {
  var title = "Lorem";
  return (
    <div className={styles.container}>
      <Header title={title} />
      <Sidebar index={4} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoremMain />
    </div>
  );
}
