import Head from "next/head";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import TargetsMain from "../components/targetsMain";
import styles from "../styles/Home.module.css";

export default function Targets() {
  var title = "Targets";
  return (
    <div className={styles.container}>
      <Header title={title} />
      <Sidebar index={3} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TargetsMain />
    </div>
  );
}
